### ISSUE TITLE
Provide an option to directly open the trace file in the https://trace.playwright.dev/ for each test in a new tab, instead of having to download and open it separately.

### ISSUE THREAD

**Issue by ibrocodes7** [allure-framework/allure-js#741] opened 2023-08-05 06:24 UTC
**Is your feature request related to a problem? Please describe.**
Currently, when we run tests and generate trace files, we need to download them first and then manually open them in the Playwright Trace Viewer using the https://trace.playwright.dev/ platform. While this is functional, it can be time-consuming and adds unnecessary steps to our debugging process. By integrating a direct link to the Trace Viewer for each test, we could streamline our debugging and analysis efforts.

**Describe the solution you'd like**
To implement this feature, I suggest adding a new configuration option in the allure's settings. When enabled, the testing tool will automatically generate and display a hyperlink to the Trace Viewer for each test, opening it in a new tab upon test completion. The trace file will be loaded into the Trace Viewer.

Thank you!

**Comment by vovsemenv** [comment] 2023-08-07 08:41
duplicate of https://github.com/allure-framework/allure-js/issues/630

**Closed by vovsemenv** 2023-08-07 08:41 UTC
