### ISSUE TITLE
Support before and after hooks

### ISSUE THREAD

**Issue by just-boris** [allure-framework/allure-js#48] opened 2019-08-28 16:54 UTC
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Currently, all steps and attachments in `before` and `after` sections are getting ignored. We should provide an ability to record them to the report.

#### What is the expected behavior?

this code should work, attachment added to the report.

```
before(() => {
   allure.attachment('from before', 'hello!', ContentType.TEXT);
})
```
#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | jest@latest |
| Allure adaptor | allure-mocha@latest |
| Generate report using | allure-jenkins@latest |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by guitartsword** [comment] 2020-02-03 17:41
I want to add a file with the current test on an afterEach
```
afterEach(function () {
  allure.attachment('File att', 'File Data', ContentType.TEXT);
  allure.testAttachment('File tatt', 'File Data', ContentType.TEXT);
  allure.createAttachment('File catt', 'File Data', ContentType.TEXT);
});
```

Opening the `allure-results` folder I can see the attachment was created, but the test doesn't have the files. I guess the problem is that the `afterEach` hook is treated as another test case and this test case is not generated causing the attachment that created not to be link to a test case.

What we want is something like the following:

- **before Hook:** should have all the allure config in the first test case from the describe block
- **after Hook:** same as before hook, only that the allure calls should be linked to the last test case
- **beforeEach & afterEach Hooks:** This should be linked to the test that this hook is related


```
describe('Suite Name', function () {
  before(function () {
    allure.tag('first');
    allure.tag('before');
  });
  after(function () {
    allure.tag('last');
    allure.tag('after');
  });
  beforeEach(function () {
    allure.tag('beforeEach');
  });
  afterEach(function () {
    allure.tag('afterEach');
  });
  it('Test One', function () {
    allure.issue('1', 'https://www.example.com?issue=1');
  });
  it('Test Two', function () {
    allure.issue('2', 'https://www.example.com?issue=2');
  });
  it('Test Three', function () {
    allure.issue('3', 'https://www.example.com?issue=3');
  });
});
```

Notes:
- BeforeEach Hook is working
- AfterEach Hook should do the same as BeforeEach Hook, create and afterEach tag for each test
- Before Hook causes 'Error: No test running!' (this seems a bit difficult to resolve)
- After Hook should create the tags for the test labeled "Test Three"

**Comment by sskorol** [comment] 2020-05-03 20:09
`after` hook should work as soon as #138 is merged and a new version is released.
In terms of `before` hook, there's an issue in Mocha (https://github.com/mochajs/mocha/issues/4266) which adds a confusion to the current codebase. So at least we should wait until it's fixed.

**Closed** 2024-04-10 11:43 UTC
Labels: theme:jest
