### ISSUE TITLE
allure is undefined during mocha runtime

### ISSUE THREAD

**Issue by jee-lee** [allure-framework/allure-js#496] opened 2022-09-07 14:27 UTC
Hello!
I am seeing this occurring when I try to run mocha in my es6 js project. The allure object is undefined while running mocha.
I am using node 16.13.1
mocha 9.2.0 and allure-mocha 2.0.0-beta.19

```javascript
import { expect } from 'chai';
import { allure } from 'allure-mocha/runtime.js';

describe('example test suite', () => {
  it('is some test', async => {
    allure.epic('Some info');
    const someNumber = 1;
    const newNumber = someNumber + 1;
    expect(newNumber).to.equal(2)
  })
})
```

I've attached my example project.
[example-js-allure.zip](https://github.com/allure-framework/allure-js/files/9478923/example-js-allure.zip)

_Originally posted by @jee-lee in https://github.com/allure-framework/allure-js/issues/50#issuecomment-1235602677_

**Comment by epszaw** [comment] 2022-10-17 09:31
Hello! The problem is described here #486

**Comment by baev** [comment] 2022-10-19 05:17
Duplicate of #486

**Closed by baev** 2022-10-19 05:17 UTC
Labels: type:bug, theme:mocha
