### ISSUE TITLE
file path is missing in Suite overview on latest version of allure 

### ISSUE THREAD

**Issue by ibrocodes7** [allure-framework/allure-js#623] opened 2023-02-22 06:39 UTC
**Describe the bug**
Earlier in the suite section, file paths are used a first level reference and expanding it would show the describe suite titles. But now, suite titles are shown instead.

**To Reproduce**
1. Go to allure report overview
2. Click on 'show all' 
3. See error

**Expected behavior**
The tree structure of the Suite should have the file path as well.

**Screenshots**
![SCR-20230222-g3u](https://user-images.githubusercontent.com/65076139/220542609-969e3437-7d3f-4b65-86ec-0a19c9d7a5cb.png)
![SCR-20230222-g5n](https://user-images.githubusercontent.com/65076139/220542612-82a340a7-6566-4ebe-9ae8-fec1f120fa1c.png)

**Desktop (please complete the following information):**
 - OS: darwin, linux
 - Browser: Chromium
 - Version:
    "allure-commandline": "^2.21.0",
    "allure-playwright": "^2.0.0",

**Comment by baev** [comment] 2023-02-22 07:52
There is the configuration option is available to configure such behavior, see https://github.com/allure-framework/allure-js/tree/master/packages/allure-playwright#suit-title

**Comment by ibrocodes7** [comment] 2023-02-22 08:06
@baev setting suiteTitle property to true generated with filePath. Thank you! It used to be true by default, in older versions, isn't?

**Comment by baev** [comment] 2024-07-01 18:08
https://github.com/allure-framework/allure-js/pull/1033 will allow you to use the `Packages` tab to see the tests grouped by test files.

I agree that, by default, the report should show the tests grouped by spec paths and then additionally grouped by describes (if any). The problem is that Allure 2 currently has limitations that prevent the proper implementation of the report this way. The good news is that it's already planned for Allure 3.

Closing this issue right now since `suiteTitle` and `details` are set to `true` by default in the current version (3.0.0-beta.4)

**Closed by baev** 2024-07-01 18:08 UTC
Labels: theme:playwright
