### ISSUE TITLE
Add allure.step() API to the allure-playwright

### ISSUE THREAD

**Issue by AlexKomanov** [allure-framework/allure-js#432] opened 2022-04-04 11:05 UTC
Hi,  team!

We have a lot of useful APIs with the allure object.

It will be great to get an API for allure.step in order to customize the allure report.
For example, it will allow an option to provide some custom names of elements to the allure step in the report:

  ```
  private page: Page;
    private locator: string;
    private allureAnnotation: string


    constructor(page: Page, locator: string, allureAnnotation: string) {
        this.page = page;
        this.locator = locator;
        this.allureAnnotation = allureAnnotation;
    }

    async click() {
        const element = this.page.locator(this.locator);
        await element.waitFor();
        await element.click();
        allure.step(`Clicking on ${this.allureAnnotation} element`)
    }



```

**Comment by baev** [comment] 2022-04-04 11:17
Duplicate of https://github.com/allure-framework/allure-js/issues/373

**Closed by baev** 2022-04-04 11:17 UTC
