### ISSUE TITLE
Not working in Hermione 8

### ISSUE THREAD

**Issue by dicrtarasov** [allure-framework/allure-js#861] opened 2024-02-04 12:44 UTC
Version: 2.9.x

Config:
```
        'allure-hermione': {
            resultsDir: './allure-results',
            enabled: false
        },
```

Error in console:
```
[18:18:08 GMT+3] TypeError: Cannot read properties of undefined (reading 'on')
    at Hermione.<anonymous> (/place/db/www/login/.tests/node_modules/allure-hermione/dist/index.js:163:25)
    at Hermione.emit (node:events:514:28)
    at MainRunner.<anonymous> (/place/db/www/login/.tests/node_modules/hermione/build/src/events/utils.js:5:55)
    at MainRunner.emit (node:events:514:28)
    at WorkersRegistry.<anonymous> (/place/db/www/login/.tests/node_modules/hermione/build/src/events/utils.js:5:55)
    at WorkersRegistry.emit (node:events:514:28)
    at WorkersRegistry._initChild (/place/db/www/login/.tests/node_modules/hermione/build/src/utils/workers-registry.js:111:14)
    at Object.onChild (/place/db/www/login/.tests/node_modules/hermione/build/src/utils/workers-registry.js:56:36)
    at Farm.startChild (/place/db/www/login/.tests/node_modules/worker-farm/lib/farm.js:117:16)
    at Farm.setup (/place/db/www/login/.tests/node_modules/worker-farm/lib/farm.js:69:12)
    at farm (/place/db/www/login/.tests/node_modules/worker-farm/lib/index.js:16:15)
    at WorkersRegistry._createWorkerFarm (/place/db/www/login/.tests/node_modules/hermione/build/src/utils/workers-registry.js:59:16)
    at WorkersRegistry.init (/place/db/www/login/.tests/node_modules/hermione/build/src/utils/workers-registry.js:26:33)
    at MainRunner.init (/place/db/www/login/.tests/node_modules/hermione/build/src/runner/index.js:62:30)
    at Hermione.run (/place/db/www/login/.tests/node_modules/hermione/build/src/hermione.js:66:16)
    at async Command.<anonymous> (/place/db/www/login/.tests/node_modules/hermione/build/src/cli/index.js:59:36)
```

**Comment by epszaw** [comment] 2024-02-04 19:45
Duplicate of #853

**Closed** 2024-02-26 11:46 UTC
Labels: type:bug, theme:hermione
