### ISSUE TITLE
flag to merge stdout events or turn them off as attachments

### ISSUE THREAD

**Issue by ajaskolski** [allure-framework/allure-js#356] opened 2021-09-09 06:22 UTC
I use allure-playwright.

At the moment every stdout event create new attachment to allure which can be annoying when You some loggers on. 

As user we also want to have 1 gathered file with all logs or possibility to turn it off.

Add flag/options to turn off stdout from tests or possibility to merge them into 1 file.
st here.

**Comment by vovsemenv** [comment] 2022-11-28 10:27
duplicate of https://github.com/allure-framework/allure-js/issues/500 fill be fixed soon

**Closed by vovsemenv** 2022-11-28 10:27 UTC
Labels: theme:playwright

**Comment by vovsemenv** [comment] 2023-01-23 14:22
PR is ready guys 😻
https://github.com/allure-framework/allure-js/pull/580
