### ISSUE TITLE
Support for Cucumber.js version 5

### ISSUE THREAD

**Issue by korobochka** [allure-framework/allure-js#14] opened 2019-01-29 17:57 UTC
Currently allure-cucumberjs works with version `"cucumber": "^4.2.1"` at most.

With Cucumber.js 5+ reporter fails with the message:
`Error: TypeError: Class constructor Formatter cannot be invoked without 'new'
at new CucumberJSAllureFormatter`

Some additional information:
https://github.com/korobochka/cucumberjs-allure2-reporter/issues/4

**Comment by fescobar** [comment] 2019-04-04 11:14
Hi @korobochka 
Do you have any update about this?
Thank you

**Comment by fescobar** [comment] 2019-04-04 11:26
I tried with all version and It worked.
The problem is only in the last version **5.1.0** >  https://www.npmjs.com/package/cucumber/v/5.1.0

https://www.npmjs.com/package/cucumber

**Comment by sseliverstov** [comment] 2019-05-28 09:47
There were wrong compile options. Fixed in beta.2

**Closed by sseliverstov** 2019-05-28 09:47 UTC
