### ISSUE TITLE
allure-cucumberjs is not supporting @cucumber/cucumber version 7.3.2

### ISSUE THREAD

**Issue by Alje001** [allure-framework/allure-js#429] opened 2022-03-10 20:06 UTC
**Describe the bug**
I am using @cucumber/cucumber version Number 7.3.2 with allure-cucumberjs Version 2.0.0-beta.15 and I am getting the error.  
Error: Cannot find module 'cucumber'

My reporter code is :
```
import { CucumberJSAllureFormatter, AllureRuntime } from 'allure-cucumberjs';

function Reporter(options: any) {
  return new CucumberJSAllureFormatter(
    options,
    new AllureRuntime({ resultsDir: './allure-results' }),
    {},
  );
}

Reporter.prototype = Object.create(CucumberJSAllureFormatter.prototype);
Reporter.prototype.constructor = Reporter;

exports.default = Reporter;
```

it seems that allure-cucumberjs doesn't support latet cucmber version. 

can you support me please ?

**Comment by mcm-ham** [comment] 2022-03-16 04:45
Looks like duplicate of #227. Need to use cucumber 6 in the meantime.

**Comment by baev** [comment] 2022-06-24 12:06
Duplicate of #227

**Closed by baev** 2022-06-24 12:06 UTC
Labels: theme:cucumberjs
