### ISSUE TITLE
Cucumber.js - Cannot use Metadata to organize tests by Epic, Story and Suites

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure-js#851] opened 2024-01-25 14:30 UTC
**Describe the bug**
According to the documentation https://allurereport.org/docs/cucumberjs/, I should be able to organize by tests by using:
```
this.epic("Web interface");
this.feature("Essential features");
this.story("Authentication");
this.parentSuite("Web interface");
this.suite("Essential features");
this.subSuite("Authentication");
```

Unfortunately, it doesn't work.
I get errors like:
```
TypeError: this.epic is not a function
    at World.<anonymous>
```

**To Reproduce**

`reporter.js` file:
```
const { CucumberJSAllureFormatter } = require("allure-cucumberjs");
const { AllureRuntime } = require("allure-cucumberjs");

function Reporter(options) {
  return new CucumberJSAllureFormatter(
    options,
    new AllureRuntime({ resultsDir: "./reporting/allure-results/nodejs-results" }),
    {}
  );
}
Reporter.prototype = Object.create(CucumberJSAllureFormatter.prototype);
Reporter.prototype.constructor = Reporter;

exports.default = Reporter;
```

`cucumber.js` file:
```
const path = require("path");

module.exports = {
  default: {
    format: [path.resolve(__dirname, "reporter.js")],
  },
};
```

The feature:
```
const assert = require('assert');
const { Given, When, Then } = require('@cucumber/cucumber');
const Calculator = require('../../model/calculator');


Given("I have a calculator", () => {
  this.calculator = new Calculator();
});


When("I add {int} and {int}", (x, y) => {
  this.sum = this.calculator.add(x, y);
});


Then("The calculator returns {int}", (sum) => {
  this.epic("Cucumber");
  this.feature("Calculator");
  this.story("Addition");
  this.parentSuite("Cucumber");
  this.suite("Calculator");
  assert.equal(this.sum, sum)
});
```

When I execute the test and generate the report, I get:
```
TypeError: this.epic is not a function
    at World.<anonymous>
```

**Expected behavior**
All these functions should work properly:
```
this.epic("Web interface");
this.feature("Essential features");
this.story("Authentication");
this.parentSuite("Web interface");
this.suite("Essential features");
this.subSuite("Authentication");
```

**Screenshots**
![image](https://github.com/allure-framework/allure-js/assets/16239820/a64fb2f1-2427-4e13-a03f-6c1edc435108)

**Desktop (please complete the following information):**
 - OS: Debian 12 bookworm
 - Browser [chrome]
- Allure: 2.26.0

**Comment by epszaw** [comment] 2024-01-29 09:37
Hey there! You can't use `this` with arrow functions in step definitions ([see official docs](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/step_definitions.md#cucumber-expressions)). Change arrow function on plan one and functionality should work as expected

**Comment by harmin-parra** [comment] 2024-01-29 21:13
It also fails when using this piece of code

```
Then("The calculator returns {int}", function(sum) {
  this.epic("Cucumber");
  this.feature("Calculator");
  this.story("Addition");
  this.parentSuite("Cucumber");
  this.suite("Calculator");
  assert.equal(this.sum, sum);
});

```

**Comment by epszaw** [comment] 2024-01-30 10:08
Could you provide an example repository, where I'll be able to reproduce the problem?

**Comment by harmin-parra** [comment] 2024-01-30 15:53
https://github.com/harmin-parra/calculator

Can be used for both #851 and #852

**Comment by epszaw** [comment] 2024-02-01 17:12
Closing because the issue is a copy of #852

**Closed by epszaw** 2024-02-01 17:12 UTC
Labels: theme:cucumberjs
