### ISSUE TITLE
allure-mocha doesn't work with parallel mode = true

### ISSUE THREAD

**Issue by annivanova1992** [allure-framework/allure-js#419] opened 2022-02-03 11:13 UTC
**Describe the bug**
Running tests with parallel mode breaks test results

**Error**:
`"statusDetails":{
      "message":"hook.error is not a function",
      "trace":"TypeError: hook.error is not a function\n    at MochaAllureReporter.onHookEnd (node_modules/allure-mocha/dist/MochaAllureReporter.js:67:40)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
   }`

**Environment**:
mocha 9.1.3
allure-mocha 2.0.0-beta.15 
mocha.parallelMode(true)

**Comment by just-boris** [comment] 2022-02-03 22:07
Duplicate of https://github.com/allure-framework/allure-js/issues/245

Please, follow the other issue for any updates

**Closed by just-boris** 2022-02-03 22:07 UTC

**Comment by darkallure** [comment] 2022-08-18 13:43
I still have this issue, is it fixed already?

**Comment by baev** [comment] 2022-08-18 16:18
@darkallure please do not comment on closed issues, create a new one instead. Make sure you are using latest release available (`v2.0.0-beta.19` at the moment)
