### ISSUE TITLE
Console.logs are shown as stdout files

### ISSUE THREAD

**Issue by florin-talarian** [allure-framework/allure-js#333] opened 2021-08-20 13:49 UTC
**Describe the bug**
Issues with playwright allure report

**To Reproduce**
- npx playwright test --browser=chromium --reporter=line,allure-playwright
- allure generate ./allure-results -c && allure open 

**Expected behavior**
I would expect to see the The console.logs directly in the test case

**Screenshots**
I'm seeing for each log a stdout file that contains the log.
![image](https://user-images.githubusercontent.com/85933919/130242979-8d0b1516-0943-439e-9bed-8be19f0d1ead.png)
I need to click every file to see the log

**Desktop (please complete the following information):**
 - Browser chromium 

And a question: is how to attach screenshots to the allure reports? 
I'm using latest playwright version with playwright test runner

Thank you very much!

**Comment by ur-av** [comment] 2022-08-09 12:46
@vovsemenv seeing the same issue, it's been over a year, any chance this issue would be sorted?

**Comment by vovsemenv** [comment] 2022-11-28 09:26
duplicate of https://github.com/allure-framework/allure-js/issues/500 fill be fixed soon

**Closed by vovsemenv** 2022-11-28 09:26 UTC
Labels: theme:playwright

**Comment by vovsemenv** [comment] 2023-01-23 14:22
PR is ready guys 😻
https://github.com/allure-framework/allure-js/pull/580
