### ISSUE TITLE
Label "Unknown" incorrect in retries tab with retry policy

### ISSUE THREAD

**Issue by carri747** [allure-framework/allure-js#826] opened 2023-12-27 14:53 UTC
**Describe the bug**
I'm using wdio in the latest version, when I've a retry policy defined and my test fail the first time and in the second try is success.
When I generate a report I can see in "Retry" tab the label "unknow" when the first execution was failed.

**To Reproduce**
1. Download this branch [https://github.com/carri747/carri747/tree/allureissue](url)
2. Execute `npm i`
3. Execute `npm run wdio `
4. Check in console that you have the same test failing the first time and the second working
5.  Run `npm run report:generate`
6. Run `npm run report:open`
7. Open Allure report 
8. Open the testcase and go to "Retries" tab

**Expected behavior**
The result that it's shown in "Retries" tab should be "Fail" because the error it's known 

**Screenshots**
![image](https://github.com/allure-framework/allure-js/assets/22347831/1e67c44f-aa9f-4ed1-87dc-929e18eff994)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome,]

**Comment by epszaw** [comment] 2023-12-28 16:57
Hey, @carri747! Will take a look on the problem

**Comment by carri747** [comment] 2024-01-22 08:12
Hello,
any news about this issue?
Thanks

**Comment by epszaw** [comment] 2024-01-22 09:41
Hey, @carri747! At this moment, I don't have any news. I reproduced the bug, but didn't figure out what's going wrong due to a lack of time. Will investigate the problem once more as soon as possible and notify you about the progress!

**Comment by epszaw** [comment] 2024-01-30 14:36
Hey, @carri747! The problem has been solved [in the PR](https://github.com/webdriverio/webdriverio/pull/12129)

**Comment by epszaw** [comment] 2024-01-31 09:50
The PR was merged, closing the issue

**Closed by epszaw** 2024-01-31 09:50 UTC
Labels: type:bug, theme:wdio
